name: Ushasree Frontend CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions: write-all   # Needed for pushing changes back to main

jobs:
  uss-frontend-ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint . --ext .js,.jsx,.ts,.tsx

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: .
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Run Unit Tests
        run: npm test -- --ci --coverage

      - name: Build App
        run: npm run build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set version from git commit count
        id: version
        run: |
          version=$(git rev-list --count HEAD)
          echo "VERSION=$version" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/uss-frontend:v${{ steps.version.outputs.VERSION }} .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/uss-frontend:v${{ steps.version.outputs.VERSION }}
          format: 'table'
          exit-code: '0'
          ignore-unfixed: true

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/uss-frontend:v${{ steps.version.outputs.VERSION }}

      # --- Install yq for YAML editing ---
      - name: Install yq
        run: |
          sudo wget https://github.com/mikefarah/yq/releases/download/v4.44.1/yq_linux_amd64 -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # --- Update deployment.yaml image tag ---
      - name: Update deployment.yaml with new image tag
        run: |
          yq -i '
            .spec.template.spec.containers[] |=
              select(.name == "uss-frontend") .image = "${{ secrets.DOCKERHUB_USERNAME }}/uss-frontend:v${{ steps.version.outputs.VERSION }}"
            ' k8s/deployment.yaml

      # --- Commit, rebase, and push the updated deployment.yaml (with retry loop) ---
      - name: Commit, rebase, and push updated deployment.yaml
        run: |
          git config --global user.email "nvvr53@gmail.com"
          git config --global user.name "nvvrsre"
          git add k8s/deployment.yaml
          git commit -m "ci: update frontend image to v${{ steps.version.outputs.VERSION }}" || echo "No changes to commit"
          # Retry logic for git pull --rebase and push
          n=0
          until [ $n -ge 3 ]
          do
            git pull --rebase origin main && git push origin main && break
            n=$((n+1))
            echo "Push failed, retrying ($n/3)..."
            sleep 2
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
